/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddPlaceRouteImport } from './routes/add-place'
import { Route as PlaceSlugRouteImport } from './routes/place.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddPlaceRoute = AddPlaceRouteImport.update({
  id: '/add-place',
  path: '/add-place',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaceSlugRoute = PlaceSlugRouteImport.update({
  id: '/place/$slug',
  path: '/place/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-place': typeof AddPlaceRoute
  '/place/$slug': typeof PlaceSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-place': typeof AddPlaceRoute
  '/place/$slug': typeof PlaceSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-place': typeof AddPlaceRoute
  '/place/$slug': typeof PlaceSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/add-place' | '/place/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/add-place' | '/place/$slug'
  id: '__root__' | '/' | '/add-place' | '/place/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddPlaceRoute: typeof AddPlaceRoute
  PlaceSlugRoute: typeof PlaceSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-place': {
      id: '/add-place'
      path: '/add-place'
      fullPath: '/add-place'
      preLoaderRoute: typeof AddPlaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/place/$slug': {
      id: '/place/$slug'
      path: '/place/$slug'
      fullPath: '/place/$slug'
      preLoaderRoute: typeof PlaceSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddPlaceRoute: AddPlaceRoute,
  PlaceSlugRoute: PlaceSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
